#include "completions.hpp"
#include "commands.hpp"
#include "ui.hpp"
#include <iostream>
#include <set>
#include <sstream>

namespace {

// Wraps text in single quotes for any POSIX-ish shell.
std::string sq(const std::string& s) {
    std::string out = "'";
    for (char c : s) out += c == '\'' ? std::string("'\\''") : std::string(1, c);
    return out + "'";
}

// Escapes characters special inside zsh _arguments/_describe specs.
std::string zshEscape(const std::string& s) {
    std::string out;
    for (char c : s) {
        if (c == '[' || c == ']' || c == ':' || c == '\\') out += '\\';
        out += c;
    }
    return out;
}

std::string categoryList(const Config& config) {
    std::string out;
    for (const auto& c : config.categories) out += c.folder + " ";
    return out + "Other";
}

// How to complete an option's value, per shell.
struct ValueHint {
    std::string zsh;   // action after "message:"
    std::string bash;  // compgen arguments
    std::string fish;  // complete arguments
};

ValueHint hintFor(const OptionSpec& o, const Config& config) {
    if (o.value_name == "DIR" || o.long_name == "in") return {"_files -/", "-d", "-xa '(__fish_complete_directories)'"};
    if (o.value_name == "FILE") return {"_files", "-f", "-rF"};
    if (o.long_name == "sort") return {"(date size name)", "-W 'date size name'", "-xa 'date size name'"};
    if (o.long_name == "type") {
        std::string cats = categoryList(config);
        return {"(" + cats + ")", "-W '" + cats + "'", "-xa '" + cats + "'"};
    }
    return {" ", "", "-x"};  // free-form value (sizes, ages, numbers)
}

void zsh(const Config& config) {
    std::ostringstream o;
    auto optSpecs = [&](const std::vector<OptionSpec>& opts) {
        std::string out;
        for (const auto& opt : opts) {
            std::string desc = "[" + zshEscape(opt.help) + "]";
            std::string value;
            if (!opt.value_name.empty()) value = ":" + zshEscape(opt.value_name) + ":" + hintFor(opt, config).zsh;
            if (opt.short_name) {
                std::string excl = "(-" + std::string(1, opt.short_name) + " --" + opt.long_name + ")";
                out += "    " + sq(excl + "-" + std::string(1, opt.short_name) + desc + value) + "\n";
                out += "    " + sq(excl + "--" + opt.long_name + desc + value) + "\n";
            } else {
                out += "    " + sq("--" + opt.long_name + desc + value) + "\n";
            }
        }
        return out;
    };

    o << "#compdef filemgr\n# zsh completion for filemgr (generated by 'filemgr completions zsh')\n\n"
      << "_filemgr_rules() {\n  local -a rules\n  rules=(${(f)\"$(filemgr clean --names 2>/dev/null)\"})\n"
      << "  _describe 'rule' rules\n}\n\n"
      << "_filemgr() {\n  local curcontext=\"$curcontext\" state line\n  local -a global_opts commands\n"
      << "  global_opts=(\n" << optSpecs(globalOptions()) << "  )\n  commands=(\n";
    for (const auto& c : commands()) o << "    " << sq(c.name + ":" + zshEscape(c.summary)) << "\n";
    o << "  )\n\n  _arguments -C $global_opts '1:command:->command' '*::argument:->argument'\n"
      << "  case $state in\n    command) _describe 'command' commands ;;\n    argument)\n      case $words[1] in\n";
    for (const auto& c : commands()) {
        o << "        " << c.name << ")\n          _arguments $global_opts \\\n" ;
        std::string specs = optSpecs(c.options);
        std::istringstream lines(specs);
        std::string line;
        while (std::getline(lines, line)) o << "        " << line << " \\\n";
        if (c.name == "config") o << "            '1:action:(show path init edit)'";
        else if (c.name == "completions") o << "            '1:shell:(zsh bash fish)'";
        else if (c.name == "clean") o << "            '*:rule:_filemgr_rules'";
        else if (c.name == "upload") o << "            '1:folder:_files -/ -W \"${FILEMGR_ROOT:-$HOME/Downloads}\"'";
        else if (c.name == "find") o << "            '*:pattern: '";
        else o << "            '*: :'";
        o << "\n          ;;\n";
    }
    o << "      esac\n      ;;\n  esac\n}\n\n_filemgr \"$@\"\n";
    std::cout << o.str();
}

void bash(const Config& config) {
    std::ostringstream o;
    auto names = [](const std::vector<OptionSpec>& opts) {
        std::string out;
        for (const auto& opt : opts) {
            out += "--" + opt.long_name + " ";
            if (opt.short_name) out += std::string("-") + opt.short_name + " ";
        }
        return out;
    };
    auto valued = [](const std::vector<OptionSpec>& opts, std::string& out) {
        for (const auto& opt : opts) {
            if (opt.value_name.empty()) continue;
            out += (out.empty() ? "" : "|") + std::string("--") + opt.long_name;
            if (opt.short_name) out += std::string("|-") + opt.short_name;
        }
    };

    std::string all_valued;
    valued(globalOptions(), all_valued);
    for (const auto& c : commands()) valued(c.options, all_valued);

    o << "# bash completion for filemgr (generated by 'filemgr completions bash')\n"
      << "_filemgr() {\n"
      << "  local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
      << "  local global=" << sq(names(globalOptions())) << "\n"
      << "  local commands=" << sq([] {
             std::string s;
             for (const auto& c : commands()) s += c.name + " ";
             return s;
         }()) << "\n"
      << "  local cmd=\"\" i w\n"
      << "  for ((i = 1; i < COMP_CWORD; i++)); do\n    w=\"${COMP_WORDS[i]}\"\n    case \"$w\" in\n"
      << "      " << all_valued << ") ((i++)) ;;\n      -*) ;;\n      *) cmd=\"$w\"; break ;;\n    esac\n  done\n\n"
      << "  case \"$prev\" in\n";
    // Value completions for options that take one.
    std::vector<OptionSpec> every = globalOptions();
    for (const auto& c : commands()) every.insert(every.end(), c.options.begin(), c.options.end());
    std::set<std::string> seen;
    for (const auto& opt : every) {
        if (opt.value_name.empty() || !seen.insert(opt.long_name).second) continue;
        std::string pat = "--" + opt.long_name + (opt.short_name ? std::string("|-") + opt.short_name : "");
        std::string hint = hintFor(opt, config).bash;
        if (hint.empty()) o << "    " << pat << ") return ;;\n";
        else o << "    " << pat << ") COMPREPLY=($(compgen " << hint << " -- \"$cur\")); return ;;\n";
    }
    o << "  esac\n\n"
      << "  if [[ -z \"$cmd\" ]]; then\n"
      << "    if [[ \"$cur\" == -* ]]; then COMPREPLY=($(compgen -W \"$global\" -- \"$cur\"));\n"
      << "    else COMPREPLY=($(compgen -W \"$commands\" -- \"$cur\")); fi\n    return\n  fi\n\n"
      << "  local opts=\"\"\n  case \"$cmd\" in\n";
    for (const auto& c : commands()) {
        if (!c.options.empty()) o << "    " << c.name << ") opts=" << sq(names(c.options)) << " ;;\n";
    }
    o << "  esac\n"
      << "  if [[ \"$cur\" == -* ]]; then COMPREPLY=($(compgen -W \"$global $opts\" -- \"$cur\")); return; fi\n\n"
      << "  case \"$cmd\" in\n"
      << "    config) COMPREPLY=($(compgen -W 'show path init edit' -- \"$cur\")) ;;\n"
      << "    completions) COMPREPLY=($(compgen -W 'zsh bash fish' -- \"$cur\")) ;;\n"
      << "    clean) local IFS=$'\\n'; COMPREPLY=($(compgen -W \"$(filemgr clean --names 2>/dev/null)\" -- \"$cur\")) ;;\n"
      << "    upload) local IFS=$'\\n'; COMPREPLY=($(cd \"${FILEMGR_ROOT:-$HOME/Downloads}\" 2>/dev/null && compgen -d -- \"$cur\")) ;;\n"
      << "  esac\n}\ncomplete -F _filemgr filemgr\n";
    std::cout << o.str();
}

void fish(const Config& config) {
    std::ostringstream o;
    auto opt = [&](const OptionSpec& s, const std::string& condition) {
        o << "complete -c filemgr" << condition;
        if (s.short_name) o << " -s " << s.short_name;
        o << " -l " << s.long_name;
        if (!s.value_name.empty()) o << " " << hintFor(s, config).fish;
        o << " -d " << sq(s.help) << "\n";
    };
    o << "# fish completion for filemgr (generated by 'filemgr completions fish')\n"
      << "complete -c filemgr -f\n";
    for (const auto& s : globalOptions()) opt(s, "");
    for (const auto& c : commands()) {
        o << "complete -c filemgr -n __fish_use_subcommand -a " << c.name << " -d " << sq(c.summary) << "\n";
        std::string cond = " -n " + sq("__fish_seen_subcommand_from " + c.name);
        for (const auto& s : c.options) opt(s, cond);
    }
    o << "complete -c filemgr -n '__fish_seen_subcommand_from config' -a 'show path init edit'\n"
      << "complete -c filemgr -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish'\n"
      << "complete -c filemgr -n '__fish_seen_subcommand_from clean' -a '(filemgr clean --names 2>/dev/null)'\n";
    std::cout << o.str();
}

} // namespace

int printCompletions(const std::string& shell, const Config& config) {
    if (shell == "zsh") zsh(config);
    else if (shell == "bash") bash(config);
    else if (shell == "fish") fish(config);
    else {
        ui::error("unsupported shell '" + shell + "' (expected zsh, bash or fish)");
        return 2;
    }
    return 0;
}
